/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package questao;


import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author gbez
 */


public class TelaPrincipal extends javax.swing.JFrame {
     
    private Comanda comanda;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtlivre = new javax.swing.JRadioButton();
        jrquilo = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxnome = new javax.swing.JTextField();
        jrcomida = new javax.swing.JRadioButton();
        jrbebida = new javax.swing.JRadioButton();
        jrcouvert = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jtpreco = new javax.swing.JTextField();
        jtadd = new javax.swing.JButton();
        jtbfinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tipo do Buffet:");

        buttonGroup1.add(jtlivre);
        jtlivre.setText("Livre");
        jtlivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtlivreActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrquilo);
        jrquilo.setText("Quilo");
        jrquilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrquiloActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jtlivre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrquilo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtlivre)
                    .addComponent(jrquilo)
                    .addComponent(jButton1))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel2.setEnabled(false);

        jLabel2.setText("Comanda:");

        jLabel3.setText("Nome do item:");

        jtxnome.setEnabled(false);
        jtxnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxnomeActionPerformed(evt);
            }
        });

        buttonGroup2.add(jrcomida);
        jrcomida.setText("Comida");
        jrcomida.setEnabled(false);

        buttonGroup2.add(jrbebida);
        jrbebida.setText(" Bebida");
        jrbebida.setEnabled(false);

        buttonGroup2.add(jrcouvert);
        jrcouvert.setText("Couvert");
        jrcouvert.setEnabled(false);

        jLabel4.setText("Preço do item: R$");

        jtpreco.setEnabled(false);

        jtadd.setText("Adicionar Item");
        jtadd.setEnabled(false);
        jtadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtaddActionPerformed(evt);
            }
        });

        jtbfinalizar.setText("Finalizar");
        jtbfinalizar.setEnabled(false);
        jtbfinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbfinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxnome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtpreco)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jrcomida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrbebida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrcouvert)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jtadd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtbfinalizar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrcomida)
                    .addComponent(jrbebida)
                    .addComponent(jrcouvert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtadd)
                    .addComponent(jtbfinalizar))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtlivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtlivreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtlivreActionPerformed

    private void jtxnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxnomeActionPerformed

    private void jtaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtaddActionPerformed
      try{
            
            
             
        if (jrcomida.isSelected()) {
            comanda.incluirItem(new Comida(jtxnome.getText(), Float.parseFloat(jtpreco.getText())));
        } 
        else if (jrbebida.isSelected()) {
            comanda.incluirItem(new Bebida(jtxnome.getText(), Float.parseFloat(jtpreco.getText())));
        } 
        else {
            comanda.incluirItem(new Couvert(jtxnome.getText(), Float.parseFloat(jtpreco.getText())));
        }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Houve um problema ao incluir seu item");
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jtaddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jtlivre.isSelected() || jrquilo.isSelected()){
        jPanel2.setEnabled(true);
        jtxnome.setEnabled(true);
        jtpreco.setEnabled(true);
        jrcomida.setEnabled(true);
        jrbebida.setEnabled(true);
        jrcouvert.setEnabled(true);
        jtadd.setEnabled(true);
        jtbfinalizar.setEnabled(true);
        }
        
         if (jtlivre.isSelected()){
                comanda = new Comanda(TipoBuffet.LIVRE);
            }
             else if (jrquilo.isSelected()){
                comanda = new Comanda(TipoBuffet.QUILO);
            }else{
             JOptionPane.showMessageDialog(this, "Houve um problema com o tipo da comanda");
             }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtbfinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbfinalizarActionPerformed
        TelaPagamento telapagamento = new TelaPagamento(comanda);    
        telapagamento.setVisible(true);
    }//GEN-LAST:event_jtbfinalizarActionPerformed

    private void jrquiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrquiloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrquiloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jrbebida;
    private javax.swing.JRadioButton jrcomida;
    private javax.swing.JRadioButton jrcouvert;
    private javax.swing.JRadioButton jrquilo;
    private javax.swing.JButton jtadd;
    private javax.swing.JButton jtbfinalizar;
    private javax.swing.JRadioButton jtlivre;
    private javax.swing.JTextField jtpreco;
    private javax.swing.JTextField jtxnome;
    // End of variables declaration//GEN-END:variables
}
