/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package questao;


import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author gbez
 */
public class TelaPagamento extends javax.swing.JFrame {
    
    private Comanda comanda;
    private Pagamento pagar;
    private Dinheiro din;

    
    /**
     * Creates new form TelaPagamento
     */
    public TelaPagamento(Comanda comanda) {
        initComponents();
        this.comanda = comanda;   
        pagar = new Pagamento(comanda);
        din = new Dinheiro(comanda, comanda.calcularValorComanda());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtcartao = new javax.swing.JRadioButton();
        jtdinheiro = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jttotal = new javax.swing.JTextField();
        jtdesconto = new javax.swing.JTextField();
        jtpago = new javax.swing.JTextField();
        jttroco = new javax.swing.JTextField();
        jtbfinalizar = new javax.swing.JToggleButton();
        jcalcular = new javax.swing.JButton();
        jtpagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Formas de Pagamento:");

        buttonGroup1.add(jtcartao);
        jtcartao.setText("Cartão");
        jtcartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcartaoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jtdinheiro);
        jtdinheiro.setText("Dinheiro");
        jtdinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtdinheiroActionPerformed(evt);
            }
        });

        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jtcartao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtdinheiro)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtcartao)
                    .addComponent(jtdinheiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jPanel2.setEnabled(false);

        jLabel2.setText("Total:              R$");

        jLabel3.setText("Desconto:       R$");

        jLabel4.setText("Pagar:             R$");

        jLabel5.setText("Troco:             R$");

        jttotal.setEnabled(false);
        jttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jttotalActionPerformed(evt);
            }
        });

        jtdesconto.setEnabled(false);

        jtpago.setEnabled(false);

        jttroco.setEnabled(false);

        jtbfinalizar.setText("Finalizar");
        jtbfinalizar.setEnabled(false);
        jtbfinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbfinalizarActionPerformed(evt);
            }
        });

        jcalcular.setText("Calcular desconto");
        jcalcular.setEnabled(false);
        jcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcalcularActionPerformed(evt);
            }
        });

        jtpagar.setText("Pagar");
        jtpagar.setEnabled(false);
        jtpagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtpagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jttotal)
                            .addComponent(jtdesconto)
                            .addComponent(jttroco, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jtpago)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jcalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtpagar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtbfinalizar)
                .addGap(65, 65, 65))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtdesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jttroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcalcular)
                    .addComponent(jtpagar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbfinalizar)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jttotalActionPerformed

    private void jtbfinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbfinalizarActionPerformed
    TelaComanda telacomanda = new TelaComanda(comanda);    
    telacomanda.setVisible(true);
    }//GEN-LAST:event_jtbfinalizarActionPerformed

    private void jtcartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcartaoActionPerformed
    
    }//GEN-LAST:event_jtcartaoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
        
      if(jtcartao.isSelected() || jtdinheiro.isSelected()){
        jPanel2.setEnabled(true);
        jttotal.setEnabled(true);
        jtdesconto.setEnabled(true);
        jtpago.setEnabled(true);
        jttroco.setEnabled(true);
        jcalcular.setEnabled(true);
        jtbfinalizar.setEnabled(true);  
        jtpagar.setEnabled(true);
        
        jttotal.setText("" + comanda.calcularValorComanda());
     }
     } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Houve um problema ao aplicar os valores");
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtpagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtpagarActionPerformed
        din = new Dinheiro(comanda, Float.parseFloat(jtpago.getText()));

        if (jtdinheiro.isSelected()) {
        jttroco.setText("" + din.calcularTroco());
        }
        else if (jtcartao.isSelected()) {
        jttroco.setText("----------------------------");
        }
    }//GEN-LAST:event_jtpagarActionPerformed

    private void jcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcalcularActionPerformed
        jtpago.setText("" + comanda.calcularValorComanda());
try{

            if (jtcartao.isSelected()) {
                if (din.calcularTotalComanda() > 50) {
            jtpago.setText("" + (comanda.calcularValorComanda() - pagar.calcularDesconto()));
            jtdesconto.setText("" + pagar.calcularDesconto());
                } else {
                    jtpago.setText("" + comanda.calcularValorComanda());
                    jtdesconto.setText("" + 0);
                }
            } else if (jtdinheiro.isSelected()) {
            jtdesconto.setText("" + din.calcularDesconto());
            }

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Houve um problema ao calcular seu troco");
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jcalcularActionPerformed

    private void jtdinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtdinheiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtdinheiroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jcalcular;
    private javax.swing.JToggleButton jtbfinalizar;
    private javax.swing.JRadioButton jtcartao;
    private javax.swing.JTextField jtdesconto;
    private javax.swing.JRadioButton jtdinheiro;
    private javax.swing.JButton jtpagar;
    private javax.swing.JTextField jtpago;
    private javax.swing.JTextField jttotal;
    private javax.swing.JTextField jttroco;
    // End of variables declaration//GEN-END:variables
}
