/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import model.Ponto;
import model.Quadrante;
/**
 *
 * @author gbez
 */
public class questao2 extends javax.swing.JFrame {

    /**
     * Creates new form questao2
     */
    public questao2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void limparCheckBox() {
        jcbEixoX.setSelected(false);
        jcbEixoY.setSelected(false);
        jcbQuadrante1.setSelected(false);
        jcbQuadrante2.setSelected(false);
        jcbQuadrante3.setSelected(false);
        jcbQuadrante4.setSelected(false);
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfX = new javax.swing.JTextField();
        jtfY = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcbEixoX = new javax.swing.JCheckBox();
        jcbEixoY = new javax.swing.JCheckBox();
        jcbQuadrante1 = new javax.swing.JCheckBox();
        jcbQuadrante2 = new javax.swing.JCheckBox();
        jcbQuadrante3 = new javax.swing.JCheckBox();
        jcbQuadrante4 = new javax.swing.JCheckBox();
        jtbavaliar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Eixo X:");

        jLabel2.setText("Eixo Y:");

        jtfX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfXActionPerformed(evt);
            }
        });

        jLabel3.setText("Posição:");

        jcbEixoX.setText("Incide sobre o Eixo X");
        jcbEixoX.setEnabled(false);
        jcbEixoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEixoXActionPerformed(evt);
            }
        });

        jcbEixoY.setText("Incide sobre o Eixo Y");
        jcbEixoY.setEnabled(false);
        jcbEixoY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEixoYActionPerformed(evt);
            }
        });

        jcbQuadrante1.setText("No Quadrante 1");
        jcbQuadrante1.setEnabled(false);

        jcbQuadrante2.setText("No Quadrante 2");
        jcbQuadrante2.setEnabled(false);

        jcbQuadrante3.setText("No Quadrante 3");
        jcbQuadrante3.setEnabled(false);

        jcbQuadrante4.setText("No Quadrante 4");
        jcbQuadrante4.setEnabled(false);

        jtbavaliar.setText("Avaliar");
        jtbavaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbavaliarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jcbEixoX)
                            .addComponent(jcbEixoY)
                            .addComponent(jcbQuadrante1)
                            .addComponent(jcbQuadrante2)
                            .addComponent(jcbQuadrante3)
                            .addComponent(jcbQuadrante4))
                        .addContainerGap(115, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfY))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfX)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtbavaliar)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbavaliar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbEixoX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbEixoY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbQuadrante1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbQuadrante2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbQuadrante3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbQuadrante4)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfXActionPerformed

    private void jcbEixoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEixoXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbEixoXActionPerformed

    private void jcbEixoYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEixoYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbEixoYActionPerformed

    private void jtbavaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbavaliarActionPerformed
         limparCheckBox();
        Ponto p = new Ponto(Integer.parseInt(jtfX.getText()),
                Integer.parseInt(jtfY.getText()));

        Quadrante quadrante = p.identificarQuadrante();

        switch (quadrante) {
            case Quadrante.PRIMEIRO:
                jcbQuadrante1.setSelected(true);
                break;
            case Quadrante.SEGUNDO:
                jcbQuadrante2.setSelected(true);
                break;
            case Quadrante.TERCEIRO:
                jcbQuadrante3.setSelected(true);
                break;
            case Quadrante.QUARTO:
                jcbQuadrante4.setSelected(true);
                break;
            case Quadrante.NENHUM:
                if (p.estaincididoSobreX()) {
                    jcbEixoX.setSelected(true);
                } else {
                    jcbEixoY.setSelected(true);
                }
                 if (p.estaincididoSobreY()) {
                    jcbEixoY.setSelected(true);
                } else {
                    jcbEixoX.setSelected(true);
                }
        }
    }//GEN-LAST:event_jtbavaliarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(questao2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(questao2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(questao2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(questao2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new questao2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox jcbEixoX;
    private javax.swing.JCheckBox jcbEixoY;
    private javax.swing.JCheckBox jcbQuadrante1;
    private javax.swing.JCheckBox jcbQuadrante2;
    private javax.swing.JCheckBox jcbQuadrante3;
    private javax.swing.JCheckBox jcbQuadrante4;
    private javax.swing.JButton jtbavaliar;
    private javax.swing.JTextField jtfX;
    private javax.swing.JTextField jtfY;
    // End of variables declaration//GEN-END:variables
}
