/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author gbez
 */
public class Relatorio extends javax.swing.JFrame {

    private TelaPrincipal tela;
    /**
     * Creates new form Relatorio
     */
    public Relatorio() {
        this.tela = tela;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaTexto = new javax.swing.JTextArea();
        buttonFechar = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jtaTexto.setColumns(20);
        jtaTexto.setRows(5);
        jScrollPane1.setViewportView(jtaTexto);

        buttonFechar.setText("Fechar");
        buttonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFecharActionPerformed
        //Para o texto não acumular, usar dessa forma:
        this.dispose();
        
        //Para o texto acumular, usar dessa forma:
        //this.setVisible(false);
    }//GEN-LAST:event_buttonFecharActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Turma turmaLocal = tela.turma;
        
        jtaTexto.append("Disciplina: " + turmaLocal.getDisciplina() + "\n");
        jtaTexto.append("Turno: " + turmaLocal.getTurno().toString() + "\n");
        jtaTexto.append("--------------------------------------");
        
        Professor p = turmaLocal.getProfessorTurma();
        jtaTexto.append("Professor: " + p.getNome() + "\n");
        jtaTexto.append("Titulacao: " + p.getTitulacao().toString() + "\n");
        jtaTexto.append("--------------------------------------");
        
        ArrayList<Aluno> alunos = turmaLocal.getListaAlunos();
        jtaTexto.append("Total de alunos: " + alunos.size() + "\n");
        for (Aluno a : alunos) {
             jtaTexto.append(a.getNome() + " " + a.getMatricula() + " - Nota Enem: " + a.getNotaEnem() + "\n");
        }
        Aluno melhorAluno = turmaLocal.obterAlunoMelhorNotaEnem();
        jtaTexto.append("Aluno(a) com a melhor nota: " + melhorAluno.getNome() + " - (" + melhorAluno.getNotaEnem() + ")");
    }//GEN-LAST:event_formWindowOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFechar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea jtaTexto;
    // End of variables declaration//GEN-END:variables
}
